"""product_model_changed

Revision ID: 307caf767254
Revises: 54dd44f0729c
Create Date: 2023-12-20 14:58:29.788311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '307caf767254'
down_revision: Union[str, None] = '54dd44f0729c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('more_about_product')
    op.add_column('product', sa.Column('version', sa.String(), nullable=True))
    op.add_column('product', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('product', sa.Column('frameworks', sa.String(), nullable=True))
    op.add_column('product', sa.Column('compatible_with', sa.String(), nullable=True))
    op.add_column('product', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'tags')
    op.drop_column('product', 'compatible_with')
    op.drop_column('product', 'frameworks')
    op.drop_column('product', 'updated_at')
    op.drop_column('product', 'version')
    op.create_table('more_about_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('frameworks', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('compatible_with', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='more_about_product_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='more_about_product_pkey')
    )
    # ### end Alembic commands ###
