"""subcribe model added

Revision ID: 6ad9c867c5ee
Revises: b9ebc8ca25bc
Create Date: 2024-01-03 22:18:12.428062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad9c867c5ee'
down_revision: Union[str, None] = 'b9ebc8ca25bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('blog_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_owner'], ['userdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('userdata_email_key', 'userdata', type_='unique')
    op.drop_constraint('userdata_username_key', 'userdata', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('userdata_username_key', 'userdata', ['username'])
    op.create_unique_constraint('userdata_email_key', 'userdata', ['email'])
    op.drop_table('blog')
    op.drop_table('subscriber')
    # ### end Alembic commands ###
