"""cart

Revision ID: a9b190da6679
Revises: 12502dfa7743
Create Date: 2023-12-23 10:18:32.025057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b190da6679'
down_revision: Union[str, None] = '12502dfa7743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
