"""product filepath added

Revision ID: b2e70febec95
Revises: dc4e5475e4ad
Create Date: 2023-12-23 11:54:00.698232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2e70febec95'
down_revision: Union[str, None] = 'dc4e5475e4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('filepath', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'filepath')
    # ### end Alembic commands ###
