"""create_table_name

Revision ID: b9ebc8ca25bc
Revises: 3bae606b51b8
Create Date: 2023-12-25 16:03:16.228885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ebc8ca25bc'
down_revision: Union[str, None] = '3bae606b51b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'userdata', ['username'])
    op.create_unique_constraint(None, 'userdata', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userdata', type_='unique')
    op.drop_constraint(None, 'userdata', type_='unique')
    # ### end Alembic commands ###
