"""product_id added

Revision ID: ca73940dd860
Revises: bff9925214a1
Create Date: 2023-12-22 09:20:41.517453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca73940dd860'
down_revision: Union[str, None] = 'bff9925214a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'product_id')
    # ### end Alembic commands ###
