"""cart

Revision ID: d39a0b86bc40
Revises: ca73940dd860
Create Date: 2023-12-22 16:46:47.400872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39a0b86bc40'
down_revision: Union[str, None] = 'ca73940dd860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('count', sa.Integer(), nullable=True))
    op.drop_column('cart', 'image')
    op.drop_column('cart', 'name')
    op.drop_column('cart', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('price', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cart', 'count')
    # ### end Alembic commands ###
