"""cart

Revision ID: dc4e5475e4ad
Revises: a9b190da6679
Create Date: 2023-12-23 11:13:48.982571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4e5475e4ad'
down_revision: Union[str, None] = 'a9b190da6679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('cart_owner_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'userdata', ['cart_owner_user_id'], ['id'])
    op.drop_column('cart', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'userdata', ['user_id'], ['id'])
    op.drop_column('cart', 'cart_owner_user_id')
    # ### end Alembic commands ###
