"""product filepath added

Revision ID: eaee0b0f6576
Revises: b2e70febec95
Create Date: 2023-12-23 12:04:29.785632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaee0b0f6576'
down_revision: Union[str, None] = 'b2e70febec95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'hash')
    # ### end Alembic commands ###
